### ISSUE TITLE
使用非erda安装时定义的集群名称添加之后无法监视和离线

### ISSUE THREAD

**Issue by 4021019** [erda-project/docs#140]
反馈一个问题：
1. 安装erda集群时定义集群名称为 devops-cluster
2. 成功安装erda之后，导入erda所在的集群时，使用名称 ycit-devops01，与之前的定义不一致
3. 然后无法在集群总览、集群资源看到 ycit-devops01 (显示未知)
4. 然后离线这个集群，则提示，下图
![image](https://user-images.githubusercontent.com/5188916/150449976-76400b9a-7022-4825-84e3-467598511d27.png)
5.我重新导入了erda集群取名为 devops-cluster 则可以正常监视
![image](https://user-images.githubusercontent.com/5188916/150450831-4b2269c9-eb02-4a78-9421-cd35dbec3083.png)

**Comment by iutx** [comment]
Master 集群对于 Erda 来说是一个特殊的集群，必须与安装时保持名称一致。
请按照安装文档流程去操作。
