### ISSUE TITLE
添加阿里云托管和自建集群报错  

### ISSUE THREAD

**Issue by lizhexun** [erda-project/docs#213]
环境：erda是用docker compose安装
描述：添加阿里云托管和自建集群，点击确定后报错 
错误：  failed to add clusters: failed to get cluster info, clusterName: erda-docker-mock, (not found)

**Comment by iutx** [comment]
@lizhexun docker-compose 定位是快速演示体验，对于这几种类型是不支持的，请选择导入已存在的kubneretes 集群
